spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/user-service2
    username: sa
    password: 

token:
  expiration_time: 86400000
  secret: 77397A24432646294A404E635166546A576E5A7234753778214125442A472D4B

gateway:
  ip: 192.168.10.96

order_service:
  # url: http://127.0.0.1:8000/order-service/%s/orders
  url: http://order-service/order-service/%s/orders
  exception:
    orders_is_empty: users's orders is empty.
